# -*- coding: utf-8 -*-
"""Proyecto_2_Resuelto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3XaVY-c9ioGIggEe6avoicPIUNqBFhr

# Parte Regresiones (Excel)

Acá priorizamos el uso de statsmodel, por simplicidad.
"""

import pandas as pd
import statsmodels.formula.api as smf

# Leemos los datos
datos = pd.read_excel("/content/Datos_Modelo.xlsx", sheet_name="Datos")

# Aseguramos que la variable categórica esté tratada como tal
datos["Tamaño_Empresa"] = datos["Tamaño_Empresa"].astype("category")

# Modelo 1: Salario ~ Experiencia
modelo_1 = smf.ols('Salario ~ Experiencia', data=datos).fit()
print(modelo_1.summary())

# Modelo 2: Salario ~ Experiencia + Años_Educación
modelo_2 = smf.ols('Salario ~ Experiencia + Años_Educación', data=datos).fit()
print(modelo_2.summary())

# Modelo 3: Salario ~ Experiencia + Años_Educación + Tamaño_Empresa (como factor)
modelo_3 = smf.ols('Salario ~ Experiencia + Años_Educación + C(Tamaño_Empresa)', data=datos).fit()
print(modelo_3.summary())

"""# Parte Machine Learning

* Implementaremos varios modelos de machine learning a la vez y en poco código.
* Priorizamos el uso de sklearn, por especialidad en machine learning.
* Separamos en entrenamiento y testeo (algo que no hicimos en Excel)
"""

# Proyecto Modelo Regresión en Python

# Cargamos las librerías
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Leemos el archivo Excel
archivo = "/content/Datos_Modelo.xlsx"
datos = pd.read_excel(archivo, sheet_name="Datos")

# Convertimos variable categórica a tipo categoría
datos["Tamaño_Empresa"] = datos["Tamaño_Empresa"].astype("category")

# Variables predictoras y objetivo
X = datos.drop(columns="Salario")
X = pd.get_dummies(X, drop_first=True)  # One-hot encoding para variables categóricas
y = datos["Salario"]

# Separamos los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

# Inicializamos los modelos
modelos = {
    "Regresión Lineal": LinearRegression(),
    "Árbol de Decisión": DecisionTreeRegressor(random_state=123),
    "Random Forest": RandomForestRegressor(random_state=123),
    "KNN": KNeighborsRegressor()
}

# Evaluamos los modelos
resultados = []

for nombre, modelo in modelos.items():
    modelo.fit(X_train, y_train)
    pred = modelo.predict(X_test)

    r2 = r2_score(y_test, pred)
    mae = mean_absolute_error(y_test, pred)
    rmse = np.sqrt(mean_squared_error(y_test, pred))

    resultados.append({
        "Modelo": nombre,
        "R2": r2,
        "MAE": mae,
        "RMSE": rmse
    })

# Mostramos los resultados
df_resultados = pd.DataFrame(resultados)
print(df_resultados)