# -*- coding: utf-8 -*-
"""Proyecto_2_Paso_a_Paso.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CgpuDzdu6iNUUNTerjHuY0fpTdH_VVSg

# Parte Regresiones (Excel)

* Priorizamos el uso de statsmodel, por especialidad en regresiones.
"""

# Cargamos las librerías
import pandas as pd
import statsmodels.formula.api as smf

# Leemos los datos
datos = pd.read_excel("/content/Datos_Modelo.xlsx", sheet_name="Datos")

# Revisamos el tipo de datos
datos.dtypes

# Aseguramos que la variable categórica esté tratada como tal
datos["Tamaño_Empresa"] = datos["Tamaño_Empresa"].astype("category")

# Revisamos el tipo de datos
datos.dtypes

# ols = Ordinary Least Squares
# Modelo 1: Salario ~ Experiencia
modelo_1 = smf.ols('Salario ~ Experiencia', data=datos).fit()
print(modelo_1.summary())

# Modelo 2: Salario ~ Experiencia + Años_Educación
modelo_2 = smf.ols('Salario ~ Experiencia + Años_Educación', data=datos).fit()
print(modelo_2.summary())

# Modelo 3: Salario ~ Experiencia + Años_Educación + Tamaño_Empresa (como factor)
modelo_3 = smf.ols('Salario ~ Experiencia + Años_Educación + C(Tamaño_Empresa)', data=datos).fit()
print(modelo_3.summary())

"""# Parte Machine Learning

* Implementaremos varios modelos de machine learning a la vez y en poco código.
* Priorizamos el uso de sklearn, por especialidad en machine learning.
* En Python se suele separar las variables predictoras de la predicha en dos dataset.
"""

# Cargamos las librerías necesarias
import pandas as pd  # Para manejo de datos en dataframes
from sklearn.model_selection import train_test_split  # Para dividir los datos en entrenamiento y prueba

# Modelos de regresión
from sklearn.linear_model import LinearRegression               # Regresión lineal
from sklearn.tree import DecisionTreeRegressor                  # Árbol de decisión
from sklearn.ensemble import RandomForestRegressor              # Random forest (conjunto de árboles)
from sklearn.neighbors import KNeighborsRegressor               # K-vecinos más cercanos (KNN)

# Métricas de evaluación del modelo
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# Para cálculos numéricos adicionales
import numpy as np

# Leemos el archivo Excel
datos = pd.read_excel("/content/Datos_Modelo.xlsx", sheet_name="Datos")
datos.head()

# Revisamos los tipos de datos
datos.dtypes

# Convertimos la variable categórica a tipo categoría
datos["Tamaño_Empresa"] = datos["Tamaño_Empresa"].astype("category")

# Revisamos los tipos de datos
datos.dtypes

# Definimos las variables predictoras
X = datos.drop(columns="Salario")

# Revisamos las columnas
X.dtypes

# Variables predictoras con Tamaño_Empresa codificada
X = pd.get_dummies(X, drop_first=True)  # One-hot encoding para variables categóricas

# Revisamos las columnas
X.dtypes

# Creamos la columna de variable dependiente
y = datos["Salario"]

# Revisamos los tipos de datos
y.dtypes

# Separamos los datos en entrenamiento y prueba (creamos 4 dataset)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=245)

# Inicializamos los modelos (almacenamos los modelos para uso futuro)
modelos = {
    "Regresión Lineal": LinearRegression(),
    "Árbol de Decisión": DecisionTreeRegressor(random_state=123),
    "Random Forest": RandomForestRegressor(random_state=123),
    "KNN": KNeighborsRegressor()
}

"""## Ejemplo en modelo de regresión lineal simple"""

# Entrenamos el modelo de Regresión Lineal (usamos uno de los 4 modelos que almacenamos)
modelo_rl = modelos["Regresión Lineal"]
modelo_rl.fit(X_train, y_train)

# Realizamos las predicciones (con la data de testeo)
predicciones = modelo_rl.predict(X_test)
predicciones

# Calculamos métricas (indicamos predicciones y datos reales testeo)
r2 = r2_score(y_test, predicciones)
mae = mean_absolute_error(y_test, predicciones)
rmse = np.sqrt(mean_squared_error(y_test, predicciones))

# Mostramos resultados
print(r2)
print(mae)
print(rmse)

modelos

# Recorramos todos los modelos creados
for nombre, modelo in modelos.items():
  print(nombre + "  ---  " + str(modelo))

"""## Proyecto Final

* Tomaremos todos los contenidos vistos, y mediante un ciclo implementaremos los 4 modelos a la vez.
"""

# Creamos una lista vacía para almacenar las futuras métricas de resultados
resultados = []

# Obtenemos los resultados de los modelos
for nombre, modelo in modelos.items():

    # Ajustamos el modelo con los datos de entrenamiento
    modelo.fit(X_train, y_train)

    # Realizamos las predicciones para los datos de testeo
    pred = modelo.predict(X_test)

    # Obtenemos las métricas para los datos de testeo
    r2 = r2_score(y_test, pred)
    mae = mean_absolute_error(y_test, pred)
    rmse = np.sqrt(mean_squared_error(y_test, pred))


    # Añadimos los resultados al dataframe
    resultados.append({
        "Modelo": nombre,
        "R2": r2,
        "MAE": mae,
        "RMSE": rmse
    })

# Mostramos los resultados
df_resultados = pd.DataFrame(resultados)
print(df_resultados)

"""## Conclusiones

* Python nos ofrece todo para implementar modelos de machine learning.
* Lo que vimos es una pequeña parte de todo lo que se puede hacer.
* Puedes reutilizar 100% este código y mejorarlo.
"""